### ISSUE TITLE
Trying to connect - we worked together for duckduckgo image api

### ISSUE THREAD

**Issue by deepanprabhu** [rachmadaniHaryono/we-get#18]
Trying to connect - we worked together for duckduckgo image api

**Comment by rachmadaniHaryono** [comment]
i will look into it tomorrow

**Comment by deepanprabhu** [comment]
sure, @rachmadaniHaryono , I am looking for a fellow developer to collaborate on projects.

**Comment by rachmadaniHaryono** [comment]
i just realize you are commenting on we-get repo.

i will close this issue. 

if you need something just create issue on your ddg repo  because i watch that repo and got notification for any new activity
