### ISSUE TITLE
No results from the_pirate_bay

### ISSUE THREAD

**Issue by phil-bell** [rachmadaniHaryono/we-get#25]
**Describe the bug**
When searching using `the_pirate_bay` as the target no matter the term used it always returns no results. Even when using the Ubuntu example on the docs. The issue happens in cli and when using the module version. 

Seems to only be `the_pirate_bay`, other targets work fine.

**To Reproduce**
1. Run `we-get --search "ubuntu" --target "the_pirate_bay"`
2. Observe that `# error:  'the_pirate_bay' - no results..` is returned

**Expected behavior**
Expected behavoir would be or valid results to be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/8983040/94368094-4f67b800-00da-11eb-9d3d-11891ead7db4.png)

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: `1.1.0`

**Comment by phil-bell** [comment]
@rachmadaniHaryono / @Hendrikto  I have a fix for this, can I have branch and PR access so I can push it up?

**Comment by Hendrikto** [comment]
@philhabell You can fork, and push a branch to your own version of the repo, then create a pull request. This is the normal Github workflow 👍

**Comment by phil-bell** [comment]
Ah nice, didn't know that 😆  

Am new to contrabuting to projects I'm not directly involved in. Thanks for lettering me know 👌
