### ISSUE TITLE
pip installation failed

### ISSUE THREAD

**Issue by mannakod** [rachmadaniHaryono/we-get#44]
Hi 

I really like this we-get, but somehow its not working, please please fix this

**Comment by Hendrikto** [comment]
Hello @mannakod, thanks for your interest and report. With the information you provided, it is very difficult to help you.

* What, exactly, is not working?
* Do you see some error message?
  * If so, what does it say?
* What did you do to get the error?
* What does your environment look like (OS, OS version, Python version, …)?
* How did you install we-get?

**Comment by mannakod** [comment]
Hi my os in Debian 11
and this is now I was accessing below 


$ pip3 install git+https://github.com/rachmadaniHaryono/we-get

Collecting git+https://github.com/rachmadaniHaryono/we-get
  Cloning https://github.com/rachmadaniHaryono/we-get to /tmp/pip-req-build-_atqg1ko
  Running command git clone -q https://github.com/rachmadaniHaryono/we-get /tmp/pip-req-build-_atqg1ko
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done


and when i run we-get command

we-get --search "royal pains" --target  the_pirate_bay,1337x --filter "S01"
-bash: we-get: command not found

python3 --version
Python 3.9.2

**Comment by rachmadaniHaryono** [comment]
basically

- install with `pipx install git+https://github.com/rachmadaniHaryono/we-get.git` is not working
- install with `pipx install .` on repo is also not working
- build with `poetry build` and `pipx install dist/we-get-1.1.3.tar.gz`  is working

i will edit the issue title

i will into it further

e:

```python
> pipx install --verbose .
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/home/r3r/.pyenv/versions/3.9.7/bin/python3'
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get
creating virtual environment...
pipx >(run_subprocess:172): running /home/r3r/.pyenv/versions/3.9.7/bin/python3 -m venv --without-pip /tmp/tmpief1496l
pipx >(run_subprocess:172): running /tmp/tmpief1496l/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/r3r/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /tmp/tmpief1496l/bin/python --version
determining package name from '/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get'...
pipx >(run_subprocess:172): running /tmp/tmpief1496l/bin/python -m pip list --format=json
pipx >(run_subprocess:172): running /tmp/tmpief1496l/bin/python -m pip install --no-dependencies /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get
pipx >(run_subprocess:172): running /tmp/tmpief1496l/bin/python -m pip list --format=json
pipx >(install_package_no_deps:283): Determined package name: UNKNOWN
pipx >(package_name_from_spec:337): Package name determined in 9.7s
creating virtual environment...
pipx >(run_subprocess:172): running /home/r3r/.pyenv/versions/3.9.7/bin/python3 -m venv --without-pip /home/r3r/.local/pipx/venvs/unknown
pipx >(run_subprocess:172): running /home/r3r/.local/pipx/venvs/unknown/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/r3r/.local/pipx/venvs/unknown/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get
installing UNKNOWN from spec '/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get'...
pipx >(run_subprocess:172): running /home/r3r/.local/pipx/venvs/unknown/bin/python -m pip install /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get
pipx >(run_subprocess:172): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:303): get_venv_metadata_for_package: 42ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/we-get
pipx >(rmdir:55): removing directory /home/r3r/.local/pipx/venvs/unknown

No apps associated with package UNKNOWN or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

**Comment by rachmadaniHaryono** [comment]
@mannakod can you confirm if https://github.com/rachmadaniHaryono/we-get/commit/8c5308919c507f412fd9772e7b17b208ae0106e6 working for you?

**Comment by mannakod** [comment]
no its not working and i tried in centos7

# pip3 install --user git+https://github.com/rachmadaniHaryono/we-get

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting git+https://github.com/rachmadaniHaryono/we-get
  Cloning https://github.com/rachmadaniHaryono/we-get to /tmp/pip-39iiorbm-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-39iiorbm-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-39iiorbm-build/

**Comment by rachmadaniHaryono** [comment]
- i don't recommend to use pip3 directly
- if you still want to use pip3 try 

```bash
pip3 install --user install git+https://github.com/rachmadaniHaryono/we-get.git
```
e:
result if using pipx
```shell
> pipx install git+https://github.com/rachmadaniHaryono/we-get.git
  installed package we-get 1.1.3, installed using Python 3.9.7
  These apps are now globally available
    - we-get
done! ✨ 🌟 ✨
```

**Comment by mannakod** [comment]
yes working fine with
> pipx install git+https://github.com/rachmadaniHaryono/we-get.git
thank you

**Comment by rachmadaniHaryono** [comment]
related issue https://github.com/python-poetry/poetry/issues/2343

i will close this

your pip command line don't have `.git` ending and https protocol, but i'm not sure if that is what affecting the failed result after https://github.com/rachmadaniHaryono/we-get/commit/8c5308919c507f412fd9772e7b17b208ae0106e6
