### ISSUE TITLE
Improve README to document install package tags with pip >10

### ISSUE THREAD

**Issue by gmt4** [rachmadaniHaryono/we-get#46]
The suggestion is just to mention on the README that pip >10 installs work :-)
See the patch attached below for an idea.

[0001-we-get-README.rst-install-from-github-using-pip-10.patch.txt](https://github.com/rachmadaniHaryono/we-get/files/8314296/0001-we-get-README.rst-install-from-github-using-pip-10.patch.txt)

**Description**

Just a minor suggestion following #45.

I've noticed that there's zip packages generated from tags under:

https://github.com/rachmadaniHaryono/we-get/tags

This is great, then I noticed that pip > 10 supports installs from pyproject.toml file

So one can do:

~~~
pip3 install https://github.com/rachmadaniHaryono/we-get/archive/refs/tags/1.1.5.tar.gz
~~~

The current README instructions for installing from pip, don't seem to work, so to install one has to:
1) fetch the repo/package
2) then build
3) then install

By using pip directly with the package tags, its basically just one step: 

1) install from pip as mentioned above.

Best,

**Comment by rachmadaniHaryono** [comment]
> The current README instructions for installing from pip, don't seem to work, so to install one has to:

you mean this part `pip3 install --user git+https://github.com/rachmadaniHaryono/we-get` ?

this should be working right?

https://pip.pypa.io/en/stable/topics/vcs-support/

https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

i keep this part so user can  install master branch directly

**Comment by gmt4** [comment]
Ignore the issue, it was caused by an error on my setup that was failing to resolve  `files.pythonhosted.org`, so I assumed that it was just not working:

~~~
$ pip install --user git+https://github.com/rachmadaniHaryono/we-get

ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f458044f2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
~~~

After solving the `files.pythonhosted.org` DNS issue it works fine:

~~~
$ pip install --user git+https://github.com/rachmadaniHaryono/we-get
...
Successfully installed we-get-1.1.5
~~~

BTW, while testing a bit more I've found that one can also install from master.zip:

~~~
$ pip install --user https://github.com/rachmadaniHaryono/we-get/archive/master.zip
...
Successfully installed we-get-1.1.5
~~~

**Comment by rachmadaniHaryono** [comment]
i will consider this closed
