### ISSUE TITLE
Error with master.zip installation on Raspbian Bullseye (Debian 11)

### ISSUE THREAD

**Issue by viertelb** [rachmadaniHaryono/we-get#47]
I installed a Raspian 11 Bullseye 32bit freshly on a Raspberry Pi 2, 
- added pip with `sudo apt install python3-pip`, 
- checked `pip --version`
   with result `pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)`, 
- updated via `python3 -m pip install --upgrade pip` 
   with result `pip 22.1.2 from /home/pi/.local/lib/python3.9/site-packages/pip (python 3.9)`
- installed `python3 -m pip install --upgrade pip setuptools wheel`
   with result `Successfully installed setuptools-62.3.2 wheel-0.37.1`
- added `/home/pi/.local/bin` to my `PATH`
- installed `we-get` with `pip install --user https://github.com/rachmadaniHaryono/we-get/archive/refs/heads/master.zip`
   with result `Successfully installed beautifulsoup4-4.11.1 charset-normalizer-2.0.12 colorama-0.4.4 docopt-0.6.2 prompt-toolkit-3.0.29 pygments-2.12.0 requests-2.27.1 soupsieve-2.3.2.post1 wcwidth-0.2.5 we-get-1.1.5`

But running it I get:
```
pi@oldRPi2:~ $ we-get -s "Dave Chappelle"
# error: Module: 'rargb.py' JSONDecodeError: Expecting value: line 1 column 1 (char 0)!
Traceback (most recent call last):ero' ...
  File "/home/pi/.local/bin/we-get", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/__init__.py", line 14, in main
    we_get.start()
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/core/we_get.py", line 256, in start
    sel.run()
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/core/we_get.py", line 172, in run
    items = run.main(self.pargs)
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/modules/il_corsaro_nero.py", line 95, in main
    return run.search()
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/modules/il_corsaro_nero.py", line 69, in search
    item = self.set_item(link)
  File "/home/pi/.local/lib/python3.9/site-packages/we_get/modules/il_corsaro_nero.py", line 43, in set_item
    seeders = re.findall(r'seeds:.*\n.*?>(.*?)<', data)[0].strip()
IndexError: list index out of range
```

we-get version 1.1.5

```
pi@oldRPi2:~ $ cat /sys/firmware/devicetree/base/model
Raspberry Pi 2 Model B Rev 1.1
pi@oldRPi2:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by viertelb** [comment]
Maybe related: https://github.com/rachmadaniHaryono/we-get/issues/24

BUT: I have a second Raspberry running for months with we-get version 1.1.2 and this works relatively fine.

**Comment by rachmadaniHaryono** [comment]
It is different issue. I guess it caused by change from the site itself.

Unfortunately i will not have my PC for weeks/months for now

Fortunately the fix is just to add index error exception here

https://github.com/rachmadaniHaryono/we-get/blob/82da686b1ad60777c44ce8b59e4c86af815a354a/we_get/core/we_get.py#L179

**Comment by viertelb** [comment]
Awesome, I will be more than happy to do it. Enjoy your holidays! :)

**Comment by viertelb** [comment]
You mean I just add the `IndexError` as exception like this: `except (IndexError, HTTPError, URLError, json.decoder.JSONDecodeError) as err:` and probably adjusting the import in that file?

What do I run to test it from within PyCharm? Running `we_get.py` seems to be missing the poetry virtualenv (I have no experience with poetry). So I tried to setup a configuration in PyCharm with core/we_get.py as script but that does also given an error (wrong path):

```

C:\Users\Ben\AppData\Local\pypoetry\Cache\virtualenvs\we-get-hxhOVtrE-py3.10\Scripts\python.exe C:/Users/Ben/PycharmProjects/we-get/we_get/core/we_get.py
Traceback (most recent call last):
  File "C:\Users\Ben\PycharmProjects\we-get\we_get\core\we_get.py", line 20, in <module>
    from we_get.core.utils import (
  File "C:\Users\Ben\PycharmProjects\we-get\we_get\core\we_get.py", line 20, in <module>
    from we_get.core.utils import (
ModuleNotFoundError: No module named 'we_get.core'; 'we_get' is not a package

Process finished with exit code 1
```

**Comment by viertelb** [comment]
I was able to activate the poetry venv in my Windows 10. Which file is the entrypoint so I can run it?

**Comment by viertelb** [comment]
Fixed with PR: https://github.com/rachmadaniHaryono/we-get/pull/48
