### ISSUE TITLE
RarGB Error

### ISSUE THREAD

**Issue by defencedog** [rachmadaniHaryono/we-get#49]
`rargb` module throws error at search

```
we-get --search "Andor" --target rargb --filter "hdr"
# error: Module: 'rargb.py' JSONDecodeError: Expecting value: line 1 column 1 (char 0)!
```

**Comment by rachmadaniHaryono** [comment]
rarbg use cloudflare now so it is harder to use it with this program

i tried to use https://github.com/venomous/cloudscraper but it raise error

`cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.`

there is other alternative, for example selenium but currently i dont want to implement that here

**Comment by defencedog** [comment]
Ok, thanks
