### ISSUE TITLE
When limiting results, sort order isn't working properly

### ISSUE THREAD

**Issue by rafi** [rachmadaniHaryono/we-get#5]
When limiting number of results (`-n`), top sorted items aren't shown. Following examples include only the first top 10 results.

First with no limit:
```sh
$ we-get --search genius -t all -q 720p
eztv ... [163/?]
eztv ... [131/?]
eztv ... [90/?]
eztv ... [76/?]
eztv ... [70/?]
the_pirate_bay ... [63/5]
eztv ... [60/?]
eztv ... [56/?]
eztv ... [53/?]
eztv ... [42/?]
```
High seeded matches are shown on the top, awesome!

But the list is too long, I just want the top 25 results:
```sh
$ we-get --search genius -t all -q 720p -n 25
eztv ... [131/?]
the_pirate_bay ... [63/5]
eztv ... [53/?]
eztv ... [42/?]
eztv ... [6/?]
eztv ... [5/?]
eztv ... [5/?]
eztv ... [5/?]
eztv ... [5/?]
eztv ... [4/?]
```
Items with much less seeds (default sort order) are shown. All the top seeded ones are missing.

Expected to see same results when limiting count.

**Comment by rachmadaniHaryono** [comment]
thanks @rafi for the bug report,

 https://github.com/rachmadaniHaryono/we-get/commit/00834dd1b6e42652250c1f008f06e3a318ac4742 should fix it, so can you try once again?

**Comment by rafi** [comment]
It works great now, thanks! :-)
