### ISSUE TITLE
aur pakage not installing due to setup.py not being found.

### ISSUE THREAD

**Issue by em2943** [rachmadaniHaryono/we-get#50]
**Describe the bug**
aur pakage not installing due to setup.py not being found.

**To Reproduce**
install we-get-git
see error

**Expected behavior**
to install we-get-git

**Screenshots**
![2023-05-22_16-16](https://github.com/rachmadaniHaryono/we-get/assets/79891947/44784496-17fc-49e9-be0a-bb00f7f96dfe)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - kernel version: 6.3.2-arch1-1

**Comment by sweetbbak** [comment]
```
# Maintainer: sweetbbak on github
_pkgname=we-get
pkgname=${_pkgname}-git
pkgver=1.1.0.r102.gf74a5f5
pkgrel=1
pkgdesc="Command-line tool for searching torrents."
#epoch=0
arch=('i686' 'x86_64')
url="https://github.com/rachmadaniHaryono/we-get"
license=('MIT')
groups=()
depends=('python-prompt_toolkit' 'python-docopt' 'python-colorama')
makedepends=()
optdepends=()
provides=()
conflicts=('we-get-git')
replaces=('we-get-git')
backup=()
options=()
source=(git+https://github.com/rachmadaniHaryono/we-get)
noextract=()
md5sums=('SKIP')

pkgver()
{
  cd "$_pkgname"
  ( set -o pipefail
    git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
  )
}

# check()
# {
  # cd "$_pkgname"
# }

prepare()
{
  cd "$_pkgname"
}

package() {
  cd ${_pkgname}
  pip3 install --user build
  # build from sources
  python3 -m build .
  python -m installer --destdir="$pkgdir" dist/*.whl
}

```
Put this PKGBUILD file in an empty directory and then cd into the PKGBUILD dir and run makepkg && paru/pacman/yay -U *.tar.gz. Refer to the arch wiki on making packages if you have any issue. I might submit this to the arch user repo since the owner hasn't in a few years

**Comment by em2943** [comment]
ok thank you
