### ISSUE TITLE
Feature to show VIP and Trusted torrents?

### ISSUE THREAD

**Issue by ghost** [rachmadaniHaryono/we-get#7]
**Is your feature request related to a problem? Please describe.**
N/A.

**Describe the solution you'd like**
To show if the torrent is VIP or from a trusted torrent provider.
An example representation could be similar to:
```
the_pirate_bay {torrent_name} [Seeders/Leechers] {VIP|Trusted}
```
The colours could be similar to the site. VIP in green, trusted in purple.

**Describe alternatives you've considered**
N/A

**Additional context**
Could such a feature be possible to implement?

**Comment by rachmadaniHaryono** [comment]
>Could such a feature be possible to implement?

depend on each site, but it will take a while

**Comment by rachmadaniHaryono** [comment]
commit added, note:

- no purple color available, so non vip user will get magenta color
- only support pirate bay for now
